# Generated by Django 4.1.5 on 2023-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='otp_code',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
