# Generated by Django 4.1.5 on 2023-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='otp_code',
            field=models.IntegerField(null=True),
        ),
    ]
