# Generated by Django 4.1.5 on 2023-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_company_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='otp_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
