# Generated by Django 4.1.4 on 2023-01-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_desk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='start_date',
        ),
    ]
