# Generated by Django 4.1.4 on 2023-01-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_desk_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
