# Generated by Django 4.1.4 on 2023-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_desk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
