# Generated by Django 4.1.5 on 2023-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_desk_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
