# Generated by Django 4.1.5 on 2023-01-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
