# Generated by Django 4.1.5 on 2023-01-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='deskCount',
            new_name='monitorCount',
        ),
    ]
