# Generated by Django 3.0.8 on 2023-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_deskcount_desk_monitorcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='uniqueID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
