# Generated by Django 4.1.5 on 2023-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_desk_id_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
