# Generated by Django 4.1.5 on 2023-01-06 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_desk_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 9, 18, 50, 968562), null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 9, 18, 50, 968545), null=True),
        ),
    ]
