# Generated by Django 4.1.5 on 2023-01-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_desk_end_date_alter_desk_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
