# Generated by Django 4.1.5 on 2023-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_desk_end_date_alter_desk_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
